# Generated by Django 5.2 on 2025-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="task",
            name="title",
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.CharField(default="New task", max_length=255),
        ),
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="finish",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=10,
            ),
        ),
    ]
