# Generated by Django 5.2 on 2025-05-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_task_completed_remove_task_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="finish",
            field=models.BooleanField(default=False),
        ),
    ]
